<!--
* Created by Henry Bravo cel 973772738.
-->
<?php
$this->inlineScript()->appendFile(
    $this->basePath() . '/public/js/reporte/desplazamiento.js'
)
?>
<style>
    a[href^="http://maps.google.com/maps"]{display:none !important}
    a[href^="https://maps.google.com/maps"]{display:none !important}

    .gmnoprint a, .gmnoprint span, .gm-style-cc {
        display:none;
    }
    .gmnoprint div {
        background:none !important;
    }
</style>
<body >

<div class="row center-align">
    <div class="col-sm-12 col-md-12">
        <div class="row " style="margin-bottom: 20px">
            <div id="map" style="width: 100%; height: 940px" ></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var directionsDisplay;
    //var lgo, lgd, lto, ltd;
    function initMap() {
        var myLatLng = {lat: -6.981017, lng: -78.514566};
        var myOptions = {
            zoom: 14,
            center: myLatLng,
            mapTypeId: 'roadmap'
        };
        directionsDisplay = new google.maps.DirectionsRenderer();
        map = new google.maps.Map(document.getElementById('map'), myOptions);

        directionsDisplay.setMap(map);

    }

</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDPt2sc_jYBhNXu48FikO9-bc0eNfbB2-A&libraries=places&sensor=false&callback=initMap">
</script>

</body>