<!--
* Created by Henry Bravo cel 973772738.
-->
<?php
    $this->inlineScript()->appendFile(
        $this->basePath() . '/public/js/reporte/ubicaciones.js'
    );
?>
<div class="row col-md-12">
    <div class="row center-align">
        <div class="col-sm-12 col-md-12">
            <div class="row">
                <!--Titulo Panel-->
                <div class="col-md-12">
                    <h1 >Reporte de ubicación de unidades</h1>
                </div>
            </div>
            <!--Lista de reportes-->
            <div class="panel panel-default text-center">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="itemre nav-item">
                            <a class="nav-link" href="#">Ubicación</a>
                        </li>
                    </ul>
                </div>
                <div class="row card-block" style="padding-top: 20px;">
                    <div class="row col-md-12">
                        <div class="card-panel col-md-12">
                            <div class="form-group  col-md-12">
                                <label for="rPalas" class="form_label col-md-1" >Palas</label>
                                <input name="tUnidad" id="rPalas" type="radio" value="1" class="col-md-1" checked>
                                <label for="rCamiones" class="form_label col-md-1" >Camiones</label>
                                <input name="tUnidad" id="rCamiones" type="radio" value="2" class="col-md-1">

                                <label class="form_label col-md-1" for="palas">Placa:</label>
                                <div  id="divPalas" class="col-md-1">
                                    <select id="palas" class="form-control col-md-12">
                                        <?php
                                            foreach ($this->palas as $value)
                                                echo "<option value='".$value['idunidad']."'>".$value['placa']."</option>";
                                        ?>
                                    </select>
                                </div>
                                <div class="col-md-1" id="divCamiones" style="display: none;">
                                    <select id="camiones" title="Placa " class="form-control col-md-12">
                                        <?php
                                        foreach ($this->camiones as $value)
                                            echo "<option class='unidad' value='".$value['idunidad']."'>".$value['placa']."</option>";
                                        ?>
                                    </select>
                                </div>
                                <label for="fDesde" class="col-md-1">Desde: </label>
                                <div class="col-md-1">
                                    <input id="fDesde"  class="form-control">
                                </div>
                                <label class="col-md-1" for="fHasta">Hasta: </label>
                                <div class="col-md-1">
                                    <input id="fHasta" class="form-control">

                                </div>
                                <div class="btn btn-info col-md-2" style="margin: 0;">
                                    <i class="fa fa-code-fork" aria-hidden="true"></i>
                                    Desplazamiento
                                </div>

                            </div>
                            <div class="col-md-12"  style="background: #5f91fe1a;padding: 10px;margin-left: 1em;" id="divTable">
                                <table id="tablaUbicaciones" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline">
                                    <thead>
                                    <tr role="row">
                                        <td>Nº</td>
                                        <td>Latitud</td>
                                        <td>Longitud</td>
                                        <td>Fec. Registro</td>
                                        <td>opción</td>
                                    </tr>
                                    </thead>
                                    <tbody id="tableBodyAdd">

                                    </tbody>
                                </table>
                            </div>
                            <div class="col-md-6">
                                <a class="btn btn-info btn-xs" id="btnUpdateRoute" style="display: none"><i class="fa fa-save"></i> Actualizar</a>
                                <div id="map_canvas2" style="width: 90%;; height:500px;"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modalLoading" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content col-md-6 col-md-offset-3">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Espere un momento</h4>
            </div>
            <div class=" row modal-body">
                <div class="col-md-12">
                    <div class="col-md-4 col-md-offset-4">
                        <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
