<!--
* Created by Henry Bravo cel 973772738.
-->
<?php
    $this->inlineScript()->appendFile(
        $this->basePath() . '/public/js/reporte/ubicaciones.js'
    );
?>
<style>
    a[href^="http://maps.google.com/maps"]{display:none !important}
    a[href^="https://maps.google.com/maps"]{display:none !important}

    .gmnoprint a, .gmnoprint span, .gm-style-cc {
        display:none;
    }
    .gmnoprint div {
        background:none !important;
    }
    .modal-dialog{
        position: relative;
        display: table;
        overflow-y: auto;
        overflow-x: auto;
        width: auto;
        min-width: 1500px;
    }

</style>
<div class="row col-md-12">
    <div class="row center-align">
        <div class="col-sm-12 col-md-12">
            <div class="row">
                <!--Titulo Panel-->
                <div class="col-md-12">
                    <h1 >Reporte de ubicación de unidades</h1>
                </div>
            </div>
            <!--Lista de reportes-->
            <div class="panel panel-default text-center">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="itemre nav-item">
                            <a class="nav-link" href="#">Ubicación</a>
                        </li>
                    </ul>
                </div>
                <div class="row card-block" style="padding-top: 20px;">
                    <div class="row col-md-12">
                        <div class="card-panel col-md-12">
                            <div class="form-group  col-md-12">
                                <div class="col-md-2">
                                    <label for="rPalas" class="form_label col-md-6" >Palas</label>
                                    <label for="rCamiones" class="form_label col-md-6" >Camiones</label>
                                    <input name="tUnidad" id="rPalas" type="radio" value="1" class="col-md-6" checked>
                                    <input name="tUnidad" id="rCamiones" type="radio" value="2" class="col-md-6">
                                </div>

                                <label class="form_label col-md-1" for="palas">Placa:</label>
                                <div  id="divPalas" class="col-md-1">
                                    <select id="palas" class="form-control col-md-12">
                                        <?php
                                            foreach ($this->palas as $value)
                                                echo "<option value='".$value['idunidad']."'>".$value['placa']."</option>";
                                        ?>
                                    </select>
                                </div>
                                <div class="col-md-1" id="divCamiones" style="display: none;">
                                    <select id="camiones" title="Placa " class="form-control col-md-12">
                                        <?php
                                        foreach ($this->camiones as $value)
                                            echo "<option class='unidad' value='".$value['idunidad']."'>".$value['placa']."</option>";
                                        ?>
                                    </select>
                                </div>
                                <label for="fDesde" class="col-md-1">Desde: </label>
                                <div class="col-md-2">
                                    <input id="fDesde"  class="form-control">
                                </div>
                                <label class="col-md-1" for="fHasta">Hasta: </label>
                                <div class="col-md-2">
                                    <input id="fHasta" class="form-control">
                                </div>
                                <a href="<?=$this->basePath().'/reporte/desplazamiento/' ?>" target="_blank" class="btn btn-info col-md-2" id="bDesplzamiento" style="margin: 0;">
                                    <i class="fa fa-code-fork" aria-hidden="true"></i>
                                    Desplazamiento
                                </a>
                            </div>
                            <div class="col-md-12"  style="background: #5f91fe1a;padding: 10px;margin-left: 1em;" id="divTable">
                                <table id="tablaUbicaciones" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline">
                                    <thead>
                                        <tr role="row">
                                            <td>Nº</td>
                                            <td>Latitud</td>
                                            <td>Longitud</td>
                                            <td>Fec. Registro</td>
                                            <td>opción</td>
                                        </tr>
                                    </thead>
                                    <tbody id="tableBodyAdd"></tbody>
                                </table>
                            </div>
                            <div class="col-md-6">
                                <a class="btn btn-info btn-xs" id="btnUpdateRoute" style="display: none"><i class="fa fa-save"></i> Actualizar</a>
                                <div id="map_canvas2" style="width: 90%;; height:500px;"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modalLoading" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content col-md-6 col-md-offset-3">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Espere un momento</h4>
            </div>
            <div class=" row modal-body">
                <div class="col-md-12">
                    <div class="col-md-4 col-md-offset-4">
                        <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="MapaPunto" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content col-md-6 col-md-offset-3">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>En el mapa</h4>
            </div>
            <div class=" row modal-body">
                <div class="col-md-12">
                    <div id="map" style="width: 600px; height: 200px" ></div>

                </div>
            </div>
        </div>
    </div>
</div>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDPt2sc_jYBhNXu48FikO9-bc0eNfbB2-A&libraries=places&sensor=false&callback=initMap">
</script>
<script type="text/javascript">
    $("#MapaPunto").on("shown.bs.modal", function () {
        google.maps.event.trigger(map, "resize");

    });

    var directionsDisplay;
    var map;
    //var lgo, lgd, lto, ltd;
    function initMap() {
        var myLatLng = {lat: -6.981017, lng: -78.514566};
        var myOptions = {
            zoom: 14,
            center: myLatLng,
            mapTypeId: 'satellite'
        };
        directionsDisplay = new google.maps.DirectionsRenderer();
        map = new google.maps.Map(document.getElementById('map'), myOptions);
        directionsDisplay.setMap(map);
    }
</script>