<!--
* Created by Henry Bravo cel 973772738.
-->
<?php
    $this->inlineScript()->appendFile(
        $this->basePath() . '/public/js/reporte/unidades.js'
    );
?>
<div class="row col-md-12">
    <div class="row center-align">
        <div class="col-sm-12 col-md-12">
            <div class="row">
                <!--Titulo Panel-->
                <div class="col-md-12">
                    <h1 >Reporte en rendimiento de unidades</h1>
                </div>
            </div>
            <!--Lista de reportes-->
            <div class="panel panel-default text-center">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="itemre nav-item">
                            <a class="nav-link" href="#">Cargas</a>
                        </li>
                    </ul>
                </div>
                <div class="row card-block" style="padding-top: 20px;">
                    <div class="row col-md-12">
                        <!--Gráfico que muestra el número de cargas -->
                        <div class="col-md-4">
                            <label>
                                Este gráfico representa el total de cargas entre un rango de fechas por pala
                            </label>
                            <div class="col-md-4" style="text-align: left">
                                <div class="col-md-12">
                                    <label for="fechadesde">Desde: </label>
                                    <input class="form-control col-md-6"  id="fechadesde">
                                </div>
                                <div class="col-md-12">
                                    <label for="fechahasta">Hasta: </label>
                                    <input class="form-control col-md-6" id="fechahasta">
                                </div>
                                <div class="col-md-12">
                                    <label for="palas">Pala: </label>
                                    <select id="palas" class="form-control">
                                        <option   value="-1">--Todas--</option>
                                        <?php
                                        foreach ($this->palas as $value)
                                            echo "<option class='palas' value='".$value['idunidad']."'>".$value['placa']."</option>";
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-8" id="conteinerCanvas">
                                <canvas id="myChart" width="100" height="100"></canvas>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label>Este gráfico representa el total de cargas por material</label>
                            <div class="col-md-4" style="text-align: left">
                                <div class="col-md-12">
                                    <label for="fechadesdeR">Desde: </label>
                                    <input class="form-control col-md-6"  id="fechadesdeR">
                                </div>
                                <div class="col-md-12">
                                    <label for="fechahastaR">Hasta: </label>
                                    <input class="form-control col-md-6" id="fechahastaR">
                                </div>
                                <div class="col-md-12">
                                    <label for="camiones">Camión: </label>
                                    <select id="camiones" class="form-control">
                                        <option   value="-1">--Todos--</option>
                                        <?php
                                        foreach ($this->camiones as $value)
                                            echo "<option class='camiones' value='".$value['idunidad']."'>".$value['placa']."</option>";
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-8" id="conteinerCanvasVolquetes">
                                <canvas id="myChartVolquetes" width="100" height="100"></canvas>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label>
                                Este gráfico representa el total de cargas por camion asignados a una pala
                            </label>
                            <div class="col-md-4" style="text-align: left">
                                <div class="col-md-12">
                                    <label for="palasCamiones">Pala: </label>
                                    <select id="palasCamiones" class="form-control">
                                        <?php
                                        foreach ($this->palas as $value)
                                            echo "<option class='palasCamiones' value='".$value['idunidad']."'>".$value['placa']."</option>";
                                        ?>
                                    </select>
                                    <label for="servicio" >Servicio</label>
                                    <select id="servicio" class="col-md-12">

                                    </select>
                                </div>
                            </div>
                            <div class="col-md-8" id="conteinerCanvasPC">
                                <canvas id="myChartPC" width="100" height="100"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modalLoading" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content col-md-6 col-md-offset-3">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Espere un momento</h4>
            </div>
            <div class=" row modal-body">
                <div class="col-md-12">
                    <div class="col-md-4 col-md-offset-4">
                        <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>