<!--
* Created by Henry Bravo cel 973772738.
-->
<?php
$this->inlineScript()->appendFile(
    $this->basePath() . '/public/js/mantenimiento/index.js'
)
?>
<style>
    textarea {

        height: 150px !important;
    }
</style>
<body onLoad="setInterval('contador()',10000);">
    <!--panel para lista de reportes-->
    <div class="row">
        <div class="panel-heading">
            <h3>Módulo de Mantenimiento</h3>
        </div>

        <div class="panel-body">
            <!--Tabla de unidades-->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            LISTA DE UNIDADES
                        </div>
                        <div class="table-responsive" id="tableDiv">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Modal para agregar unidades-->
    <div id="modalAddUnidad" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4>Nueva Unidad</h4>
                </div>
                <div class=" row modal-body">
                   <div class="card-panel col-md-12">
                       <div class="form-group col-md-12">
                           <label class="form_label col-md-2">Tipo: </label>

                           <div class="">
                               <div class="" >
                                   <div class=" col-md-1">
                                       <input class=""  type="radio" id="checkpala" name="tipounidad" value="1"  checked/>
                                   </div>
                                   <label for="checkpala" class="col-md-2">Pala</label>
                                   <div class="col-md-1">
                                       <input class=""  type="radio" id="checkvol" name="tipounidad" value="2"  />
                                   </div>
                                   <label for="checkvol" class="col-md-2">Volquete</label>
                               </div>
                           </div>
                       </div>
                       <div class="form-group  col-md-12">
                           <label class="col-md-2">Nº placa: </label>
                           <div class="col-md-10">
                               <input class="form-control col-md-12" id="nplaca" placeholder="No se debe repetir">
                           </div>
                       </div>


                       <div class="col-md-12">
                           <label class="col-md-2">Consumo: </label>
                           <div class="col-md-10">
                               <input class="form-control col-md-12" id="consumo" placeholder="En galones por hora">
                           </div>
                       </div>
                   </div>
                </div>

                <div class="modal-footer">
                    <a id="btnGuardarU" class="btn btn-info" href="#!" idu="">Guardar</a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>

        </div>
    </div>
    <!--Modal para cambiar estado-->
    <div id="changeEstado" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4>Unidad</h4>
                </div>
                <div class=" row modal-body">
                    <div class="row col-md-12" >
                        <div class="input-field col-md-5" >
                            <label for="activo" class="form-label col-md-12">Estado</label>
                            <input type="radio" id="activo" name="estado" value="1"  checked/>
                            <label for="activo">Activar</label>
                            <input type="radio" id="activo" name="estado" value="2"  />
                            <label for="activo">Desactivar</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a id="btn-confirmar" class="btn btn-info" href="#!" idc="">Confirmar</a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!--Modal cargando...-->
    <div id="modalLoading" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content col-md-6 col-md-offset-3">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4>Espere un momento</h4>
                </div>
                <div class=" row modal-body">
                    <div class="col-md-12">
                        <div class="col-md-4 col-md-offset-4">
                            <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="modalB">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title">Mantenimiento</h3>
                </div>
                <div class="row modal-body">
                    <div class="row col-md-12">
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <fieldset>
                                    <label class="col-md-12" style="margin: 0; padding: 0">Seleccione el estado actual</label>
                                    <br>
                                    <input type="radio" title="Programado" name="estadoMan" id="estado1" value="1"><label for="estado1">Programado</label>
                                    <input type="radio" title="En proceso" name="estadoMan" id="estado3" value="3"><label for="estado3">En proceso</label>
                                    <input type="radio" title="Finalizar" name="estadoMan" id="estado4" value="4"><label for="estado4">Finalizar</label>
                                    <input type="radio" title="Cancelar" name="estadoMan" id="estado2" value="2"><label for="estado2">Cancelar</label>
                                    <br>
                                    <br>
                                </fieldset>
                            </div>
                            <div class="col-md-6" >
                                <label for="fechainicio">Fecha de inicio: </label>

                                <input id="fechainicio" class="form-control">
                            </div>
                            <div class="col-md-6" id="divFF">
                                <label for="fechafinal">Fecha de finalización: </label>
                                <input id="fechafinal" class="form-control">
                            </div>
                            <div class="col-md-12"  id="divOI">
                                <label class="col-md-12" for="observaingre">Observaciones de ingreso:</label>
                                <div class = "form-group">
                                    <textarea id="observingre" class = "form-control" placeholder = "Ingresar las observaciones"></textarea>
                                </div>
                            </div>
                            <div class="col-md-12" id="divOS">
                                <label class="col-md-12" for="observasali">Observaciones de salida:</label>
                                <textarea id="observasali" class = "form-control" placeholder = "Ingresar las observaciones"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">Guardar</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</body>
