<!--
* Created by Henry Bravo cel 973772738.
-->
<?php
$this->inlineScript()->appendFile(
    $this->basePath() . '/public/js/lugar/index.js'
)
?>
<style>
    a[href^="http://maps.google.com/maps"]{display:none !important}
    a[href^="https://maps.google.com/maps"]{display:none !important}

    .gmnoprint a, .gmnoprint span, .gm-style-cc {
        display:none;
    }
    .gmnoprint div {
        background:none !important;
    }
    .modal-dialog-grande {
        width: 80%;
        height: 80%;
        margin-left: 10%;
        padding: 0;
    }

    .modal-content-grande {
        height: auto;
        min-height: 100%;
    }
</style>
<script src="<?=$this->basePath()?>/public/js/jscolor.min.js"></script>
<body >
    <div class="row center-align">
        <div class="col-sm-12 col-md-12">
            <div class="row " style="margin-bottom: 30px">
                <!--Titulo Panel-->
                <div class="col-md-12">
                    <h1>Administrador de Lugares y Rutas</h1>
                    <a class="btn btn-info btn-xs" id="btnVerDivAdd" ><i class="fa fa-plus"></i> Agregar lugar</a>
                </div>
                <!--Tabla de lugares-->
                <div class="col-md-2">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            LISTA DE LUGARES
                        </div>
                        <div class="table-responsive">
                            <table  id="table-lugares" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline tableeeeee" role="grid" aria-describedby="dataTables-example_info" style="width: 98%;">
                                <thead>
                                <tr role="row">
                                    <td>Nombre</td>
                                    <td>Estado</td>
                                    <td>opción</td>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($this->lugares as $value)
                                {
                                    $estado="";
                                    switch ($value->estado)
                                    {
                                        case 1:
                                            $estado="Activo";
                                            break;
                                        case 2:
                                            $estado="Desactivado";
                                            break;
                                    }
                                    echo "
                                    <tr>
                                        <td>".$value->nombrecompleto."(".$value->nombre.")"."</td>
                                        <td>".$estado."</td>
                                        <td>
                                            <a href='#' class='btn btn-xs btn-info estado' idl='".$value->idlugar."'>Cambiar</a>
                                            <a href='#' class='btn btn-xs btn-warning mapa' idl='".$value->idlugar."'>Mapa</a>
                                        </td>
                                    </tr>
                                    ";
                                }
                                ?>
                                </tbody>
                            </table>

                        </div>
                    </div>


                </div>
                <!--Tabla de rutas-->
                <div class="col-md-4">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            LISTA DE RUTAS
                        </div>
                        <div class="table-responsive">
                            <table  id="table-lugares" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline tableeeeee" role="grid" aria-describedby="dataTables-example_info" style="width: 98%;">
                                <thead>
                                <tr role="row">
                                    <td>Lugar Incio</td>
                                    <td>Lugar Fin</td>
                                    <td>Color</td>
                                    <td>Estado</td>
                                    <td>Opción</td>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                    foreach ($this->rutas as $value)
                                    {
                                        $estado="";
                                        switch ($value['estado'])
                                        {
                                            case 1:
                                                $estado="Activo";
                                                break;
                                            case 2:
                                                $estado="Desactivado";
                                                break;
                                        }
                                        echo "
                                        <tr>
                                            <td>".$value['nombreiniciocompleto']."(".$value["nombreinicio"].")"."</td>
                                            <td>".$value['nombrefinalcompleto']."(".$value["nombrefinal"].")"."</td>
                                            <td><input   class='jscolor col-md-8' id='jscolor".$value['idruta']."' style='margin-top: 0.3em' value='".$value['color']."' /><a idr='".$value['idruta']."' href='#' class='btn btn-xs btn-warning' onclick='saveColor(this)' ><i class='fa fa-save'> </i></a></td>
                                            <td>".$estado."</td>
                                            <td>
                                                <a href='#' class='btn btn-xs btn-warning seeroute' onclick='seeRoute(this)' idr='".$value['idruta']."' lti='".$value['latitudinicio']."' lgi='".$value['longitudinicio']."' ltf='".$value['latitudfinal']."' lgf='".$value['longitudfinal']."' ni='".$value['nombreinicio']."' nf='".$value['nombrefinal']."'><i class='fa fa-eye'>Mapa</i></a>
                                                <a href='#' class='btn btn-xs btn-info modalTxt' idr='".$value['idruta']."'  >Cambiar</a>
                                            </td>
                                        </tr>
                                        ";
                                    }
                                 ?>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
                <!--Mapa Google maps-->
                <div class="col-md-6">
                    <!--Div agregar un nuevo lugar-->
                    <div class="col-md-11" id="divaddplace" style="display:none; position: absolute; z-index: 1; background: rgba(255,181,92,0.82); padding: 10px" >
                        <div class="col-md-4">
                            <label class="label-control" for="nombrecompletoadd"  style="color:#fff">Nombre Completo</label>
                            <input class="form-control" id="nombrecompletoadd" value="" >
                        </div>
                        <div class="col-md-2">
                            <label class="label-control" for="nombreadd"  style="color:#fff">Nombre Corto</label>
                            <input class="form-control" id="nombreadd" value="" >
                        </div>
                        <div class="col-md-2">
                            <label class="label-control" for="latitud"  style="color:#fff">Latitud</label>
                            <input class="form-control" id="latitud" value="-6.981017" >
                        </div>
                        <div class="col-md-2">
                            <label class="label-control" for="longitud"  style="color:#fff">Longitud</label>
                            <input class="form-control" id="longitud" value="-78.514566">
                        </div>
                        <div class="col-md-1" style="padding-top: 10px">
                            <a class="btn btn-info btn-xs" id="btnVer" ><i class="fa fa-eye"></i> Ver</a>
                            <a class="btn btn-success btn-xs" id="btnAgregar" ><i class="fa fa-save"></i> Confirmar</a>
                        </div>
                    </div>
                    <!--Div para mostrar el mapa-->
                    <div id="map"  class="col-md-12 row" style="width: 100%; height: 700px" ></div>

                </div>
            </div>
        </div>
    </div>
    <!--Modal leer txt-->
    <div id="modalAddLugar" class="modal fade" role="dialog">
        <div class="modal-dialog modal-dialog-grande">
            <!-- Modal content-->
            <div class="modal-content modal-content-grande">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4>Cargar .TXT</h4>
                </div>
                <div class=" row modal-body">
                    <div class="card-panel col-md-12">
                        <div class="form-group  col-md-12">
                            <label class="form_label  col-md-2" >Archivo .txt: </label>
                            <input type="file" id="file-input" class="col-md-8" />
                        </div>
                        <div class="col-md-6"  >
                            <table id="editmapatable" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline">
                                <thead>
                                    <tr role="row">
                                        <td>Nº Orden</td>
                                        <td>Latitud</td>
                                        <td>Longitud</td>
                                        <td>opción</td>
                                    </tr>
                                </thead>
                                <tbody id="tableBodyAdd">
                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-info btn-xs" id="btnUpdateRoute" style="display: none"><i class="fa fa-save"></i> Actualizar</a>
                            <div id="map_canvas2" style="width: 90%;; height:500px;"></div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <a id="btnGuardarU" class="btn btn-info" href="#!" idu="">Guardar</a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>

        </div>
    </div>
    <div id="modalLoading" class="modal fade" role="dialog">
        <div class="modal-dialog" style="margin-right: auto; margin-left: auto;">

            <!-- Modal content-->
            <div class="modal-content col-md-6 col-md-offset-3">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4>Espere un momento</h4>
                </div>
                <div class=" row modal-body">
                    <div class="col-md-12">
                        <div class="col-md-4 col-md-offset-4">
                            <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <script type="text/javascript">
    var map, map2;
    var markers=[], flightPlanCoordinates = [ ];
    var directionsDisplay;
    var directionsService;
    var btnVer= document.getElementById("btnVer");
    var btnAgregar= document.getElementById("btnAgregar");
    var tableBodyAdd= document.getElementById("tableBodyAdd");
    var inputLatitud=document.getElementById("latitud");
    var inputLongitud=document.getElementById("longitud");
    var nombreadd=document.getElementById("nombreadd");
    var nombrecompletoadd=document.getElementById("nombrecompletoadd");
    var divaddplace=document.getElementById("divaddplace");
    var btnVerDivAdd=document.getElementById("btnVerDivAdd");

    //Onclick
    btnVer.onclick=agregarMarker;
    btnAgregar.onclick=addPlace;
    btnVerDivAdd.onclick=function () {
        divaddplace.style.display="block"
    };


    document.getElementById('file-input')
        .addEventListener('change', leerArchivo, false);


    //functions
    function agregarMarker() {
        var longitud=inputLongitud.value;
        var latitud=inputLatitud.value;
        addMarket(latitud, longitud);
    }
    function leerArchivo(e) {
        var archivo = e.target.files[0];
        if (!archivo) {
            return;
        }
        var lector = new FileReader();
        lector.onload = function(e) {
            var contenido = e.target.result;
            mostrarContenido(contenido);
        };
        lector.readAsText(archivo);
    }
    function mostrarContenido(contenido) {
        var lines = contenido.split(/\n/);
        var html=""
        $.each(lines, function (k,v) {
            var coordenadas = v.split(" ");

            html+="<tr><td>"+coordenadas[0]+"</td>" +
                "<td>"+coordenadas[1]+"</td>" +
                "<td>" +
                    "<a href='#' class='btn btn-xs btn-info estado'>Mapa</a>" +
                "</td></tr>";
        })
        tableBodyAdd.innerHTML = html;

    }

    function seeRoute(e) {
        var idruta=e.getAttribute("idr");
        var latitudi=e.getAttribute("lti");
        var latitudf=e.getAttribute("ltf");
        var longitudi=e.getAttribute("lgi");
        var longitudf=e.getAttribute("lgf");
        var namei=e.getAttribute("ni");
        var namef=e.getAttribute("nf");
        makePostInterno({o:2, idr:idruta});
        addMarket(latitudi, longitudi,namei, false)
        addMarket(latitudf, longitudf, namef, false)
    }
    function modalTxt(e) {
        var idruta=e.getAttribute("idr");
        modalAddLugar.modal('show')

    }
    function saveColor(e) {
        var idruta=e.getAttribute("idr");
        var jscolor=document.getElementById("jscolor"+idruta);
        var color=jscolor.value;
        makePostInterno({o:3, idr:idruta, c:color});
    }
    function agregarArrayRutas(data) {
        var color ='#FFF';
        $.each(data, function (d, k) {
            color="#"+k.color;
            flightPlanCoordinates.push({lat: parseFloat(k.latitud), lng: parseFloat(k.longitud)})
        });
        dibujarRuta(color);
    }
    function dibujarRuta(color) {
        var flightPath = new google.maps.Polyline({
            path: flightPlanCoordinates,
            geodesic: true,
            strokeColor: color,
            strokeOpacity: 1.0,
            strokeWeight: 4
        });
        flightPath.setMap(map);
    }

    function addPlace()
    {
        var nc=nombrecompletoadd.value;
        var n=nombreadd.value;
        var longitud=inputLongitud.value;
        var latitud=inputLatitud.value;

        if ((nc !== "" && n !== "")) {
            makePostInterno({o:1,nc:nc,n:n,lg:longitud,lt:latitud})
        }
        else{
            swal("error","Todos los campos son requeridos", "warning")
        }
    }

    function addMarket(latitud, longitud, title, drag) {
        var myLatLng = {lat:parseFloat(latitud), lng: parseFloat(longitud)};
        var marker = new google.maps.Marker({
            position: myLatLng,
            draggable:true,
            label: {
                color: '#2f60ff',
                fontWeight: '900',
                text: title
            },
            map: map,
            title: title
        });

    }

    function setMapOnAll(map) {

        for (key in markers) {

            var marker = markers[key];
            marker.setMap(map);
        }
        markers=[];
    }

    //var lgo, lgd, lto, ltd;
    function initMap() {
        var myLatLng = {lat: -7.173494, lng: -78.495264};
        var myOptions = {
            zoom: 14,
            center: myLatLng,
            mapTypeId: 'roadmap'
        }
        map = new google.maps.Map(document.getElementById('map'), myOptions);
        map2 = new google.maps.Map(document.getElementById("map_canvas2"), myOptions);
    }


    function makePostInterno(data){

        $.ajax({
            async: true,
            type: "POST",
            dataType: "json",
            data: data,
            url:  $("#baseUrl").val()+"/lugar/index",
            success: function (data2) {
                if(data2.data!==-1)
                {
                   switch (data.o)
                   {
                       case 1:
                           swal(
                               {
                                   title: "Agregado!!",
                                   text: "La operación del registro fue correctamente",
                                   type: "success",
                                   confirmButtonColor: "#DD6B55",
                                   closeOnConfirm: false
                               },
                               function () {
                                   location.reload(true);
                               }
                           );
                           break;
                       case 2:
                           agregarArrayRutas(data2.data)
                           break;
                       case 3:
                           location.reload(true);
                           break;
                       case 4:
                           var html="";
                           $.each(data2.data, function (k,v) {

                               html+="<tr><td>"+v.latitud+"</td>" +
                                   "<td>"+v.longitud+"</td>" +
                                   "<td>" +
                                   "<a href='#' class='btn btn-xs btn-info estado'>Mapa</a>" +
                                   "</td></tr>";
                           })
                           tableBodyAdd.innerHTML = html;
                           break;
                   }
                }
                else {
                    swal("error","Algo fue mal, intentar nuevamente en unos segundos","error")
                }
            }

        });
    }

</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDPt2sc_jYBhNXu48FikO9-bc0eNfbB2-A&libraries=places&sensor=false&callback=initMap">
</script>

</body>