<!--
* Created by Henry Bravo cel 973772738.
-->
<?php
$this->inlineScript()->appendFile(
    $this->basePath() . '/public/js/lugar/poligono.js'
)
?>
<style>
    a[href^="http://maps.google.com/maps"]{display:none !important}
    a[href^="https://maps.google.com/maps"]{display:none !important}

    .modal-backdrop{
        z-index: 998 !important;
    }

    .sinmarcos{
        z-index: 995;
    }
    .gmnoprint a, .gmnoprint span, .gm-style-cc {
        display:none;
    }
    .gmnoprint div {
        background:none !important;
    }
    .modal-dialog-grande {
        width: 80%;
        height: 80%;
        margin-left: 10%;
        padding: 0;
    }

    .modal-content-grande {
        height: auto;
        min-height: 100%;
    }
</style>
<script src="<?=$this->basePath()?>/public/js/jscolor.min.js"></script>
<body >
    <div class="row center-align">
        <div class="col-sm-12 col-md-12">
            <div class="row " style="margin-bottom: 30px">
                <!--Titulo Panel-->
                <div class="col-md-12">
                    <h1>Administrador de Polígonos</h1>
                    <a class="btn btn-info btn-xs" id="btnAddP" ><i class="fa fa-plus"></i> Agregar polígono</a>
                </div>
                <!--Tabla de lugares-->
                <div class="col-md-3">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            LISTA DE POLIGONOS
                        </div>
                        <div class="table-responsive">
                            <table  id="table-lugares" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline tableeeeee" role="grid" aria-describedby="dataTables-example_info" style="width: 98%;">
                                <thead>
                                <tr role="row">
                                    <td>Nombre</td>
                                    <td>Estado</td>
                                    <td>opción</td>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($this->poligonoes as $value)
                                {
                                    $estado="";
                                    switch ($value->estado)
                                    {
                                        case 1:
                                            $estado="Activo";
                                            break;
                                        case 2:
                                            $estado="Desactivado";
                                            break;
                                    }
                                    echo "
                                    <tr>
                                        <td>".$value->nombrecompleto."(".$value->nombre.")"."</td>
                                        <td>".$estado."</td>
                                        <td>
                                            <a href='#' class='btn btn-xs btn-warning mapa' idl='".$value->idlugar."'>Mapa</a>
                                        </td>
                                    </tr>
                                    ";
                                }
                                ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!--Mapa Google maps-->
                <div class="col-md-9">
                    <!--Div agregar un nuevo lugar-->
                    <div class="col-md-11" id="divaddplace" style="display:none; position: absolute; z-index: 1; background: rgba(255,181,92,0.82); padding: 10px" >
                        <div class="col-md-4">
                            <label class="label-control" for="nombrecompletoadd"  style="color:#fff">Nombre Completo</label>
                            <input class="form-control" id="nombrecompletoadd" value="" >
                        </div>
                        <div class="col-md-2">
                            <label class="label-control" for="nombreadd"  style="color:#fff">Nombre Corto</label>
                            <input class="form-control" id="nombreadd" value="" >
                        </div>
                        <div class="col-md-2">
                            <label class="label-control" for="latitud"  style="color:#fff">Latitud</label>
                            <input class="form-control" id="latitud" value="-6.981017" >
                        </div>
                        <div class="col-md-2">
                            <label class="label-control" for="longitud"  style="color:#fff">Longitud</label>
                            <input class="form-control" id="longitud" value="-78.514566">
                        </div>
                        <div class="col-md-1" style="padding-top: 10px">
                            <a class="btn btn-info btn-xs" id="btnVer" ><i class="fa fa-eye"></i> Ver</a>
                            <a class="btn btn-success btn-xs" id="btnAgregar" ><i class="fa fa-save"></i> Confirmar</a>
                        </div>
                    </div>
                    <!--Div para mostrar el mapa-->
                    <div id="map"  class="col-md-12 row" style="width: 100%; height: 700px" ></div>

                </div>
            </div>
        </div>
    </div>
    <!--Modal leer txt-->
    <div id="modalAddRuta" class="modal fade" role="dialog" style="z-index: 999 !important;">
        <div class="modal-dialog modal-dialog-grande">
            <!-- Modal content-->
            <div class="modal-content modal-content-grande">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4>Agregar nueva ruta</h4>
                </div>
                <div class=" row modal-body">
                    <div class="card-panel col-md-12" style="margin-bottom: 0;">
                        <div class="col-md-12">
                            <div class="col-md-4">
                                <label for="camion">Seleccionar camión</label>
                                <select class="form-control" id="camion">
                                    <option>--Selecciona--</option>
                                    <?php
                                    foreach ($camiones as $value){
                                        echo "<option value='".$value['idunidad']."'>".$value['placa']."</option>";
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <label for="fechainicio">Desde:</label>
                                <input class="form-control calendario" id="fechainicio">
                            </div>

                            <div class="col-md-3">
                                <label for="fechafin">Hasta:</label>
                                <input class="form-control calendario" id="fechafin">
                            </div>
                            <div class="col-md-2" style="padding-top: 2em">
                                <a class="btn-xs btn btn-info" id="btdShearPoint">Buscar <i class="fa fa-send"></i></a>
                            </div>
                        </div>
                        <div class="col-md-12" style="margin-bottom: 1em">
                            <div class="col-md-5">
                                <label for="lugarinicio">Lugar de inicio:</label>
                                <select class="form-control" id="lugarinicio">

                                </select>
                            </div>
                            <div class="col-md-5">
                                <label for="lugardestino">Lugar de destino:</label>
                                <select class="form-control" id="lugardestino">

                                </select>
                            </div>
                            <a class="btn-xs btn btn-info col-md-1" style="margin-top: 2em" id="btnActualizar">Actualizar <i class="fa fa-update"></i></a>

                        </div>
                        <div class="col-md-12" style="text-align: right; padding-right: 8em;">
                            <a id="btnGuardarRuta" class="btn btn-success" href="#!" idr="">Guardar</a>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        </div>
                        <div class="col-md-12">
                            <div class="col-md-6 table-responsive" id="tablapuntos">

                            </div>
                            <div class="col-md-6">
                                <div id="map_canvas_addRuta" style="width: 100%;; height:500px;"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                  </div>
            </div>
        </div>
    </div>
    <!--Modal leer txt-->
    <div id="modalAddPoligono" class="modal fade" role="dialog" style="z-index: 999 !important;">
        <div class="modal-dialog modal-dialog-grande">
            <!-- Modal content-->
            <div class="modal-content modal-content-grande">
                <div class=" row modal-body">
                    <div class="card-panel col-md-12">

                        <div class="col-md-12" style="margin-bottom: 2em">
                            <label class="form_label col-md-1" for="nColor">Color: </label>
                            <div class="col-md-3">
                                <input id="nColor" class="jscolor col-md-4 form-control" />
                            </div>
                            <label class="form_label col-md-1" for="nText">Nombre: </label>
                            <div class="col-md-3">
                                <input type="text" id="nText" class="col-md-4 form-control" />
                            </div>
                        </div>
                        <div class="form-group  col-md-12">
                            <label class="form_label  col-md-2" >Archivo .txt: </label>
                            <input type="file" id="file-input" class="col-md-8" />
                        </div>
                        <div class="col-md-6"  >
                            <table id="editmapatable" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline">
                                <thead>
                                <tr role="row">
                                    <td>Nº Orden</td>
                                    <td>Latitud</td>
                                    <td>Longitud</td>
                                    <td>opción</td>
                                </tr>
                                </thead>
                                <tbody id="tableBodyAdd">
                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-info btn-xs" id="btnUpdateRoute" style="display: none"><i class="fa fa-save"></i> Actualizar</a>
                            <div id="map_canvas2" style="width: 90%;; height:500px;"></div>f
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <a id="btnGuardarP" class="btn btn-info" href="#!" idu="">Guardar</a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
    var map, map2, mapAddRuta;
    var markers=[], flightPlanCoordinates = [ ];
    var btnVer= document.getElementById("btnVer");
    var tableBodyAdd= document.getElementById("tableBodyAdd");
    var inputLatitud=document.getElementById("latitud");
    var inputLongitud=document.getElementById("longitud");
    //Onclick
    btnVer.onclick=agregarMarker;
    document.getElementById('file-input')
        .addEventListener('change', leerArchivo, false);
    //functions
    function agregarMarker() {
        var longitud=inputLongitud.value;
        var latitud=inputLatitud.value;
        addMarket(latitud, longitud);
    }
    function leerArchivo(e) {
        var archivo = e.target.files[0];
        if (!archivo) {
            return;
        }
        var lector = new FileReader();
        lector.onload = function(e) {
            var contenido = e.target.result;
            mostrarContenido(contenido);
        };
        lector.readAsText(archivo);
    }
    function mostrarContenido(contenido) {
        var lines = contenido.split(/\n/);
        var html="";
        var array=[];
        setMapOnAll(null);
        $.each(lines, function (k,v) {
            var coordenadas = v.split(/\t/);
            if(coordenadas.length>=2){
                var ubicacionesL=coordenadas[0].split('.');
                var lat=ubicacionesL[0]+".";
                for(var x=1; x<ubicacionesL.length;x++){
                    lat+=ubicacionesL[x];
                }
                var ubicacionesLn=coordenadas[1].split('.');
                var lnt=ubicacionesLn[0]+".";
                for(var y=1; y<ubicacionesLn.length;y++){
                    lnt+=ubicacionesLn[y];
                }

                html+="<tr><td>"+coordenadas[2]+"</td>" +
                    "<td>"+lat+"</td>" +
                    "<td>"+lnt+"</td>" +
                    "<td>" +
                    "<a href='#' class='btn btn-xs btn-danger delete'><i class='fa fa-trash'></i></a>" +
                    "</td></tr>";
                array.push({latitud:lat, longitud:lnt});
                addMarket(lat, lnt, coordenadas[2]);
            }

        });
        agregarArrayRutas(array);
        tableBodyAdd.innerHTML = html;
    }

    function agregarArrayRutas(data) {
        flightPlanCoordinates=[];
        $.each(data, function (d, k) {
            flightPlanCoordinates.push({lat: parseFloat(k.latitud), lng: parseFloat(k.longitud)})
        });
        dibujarRuta("#"+$("#nColor").val());
    }
    function dibujarRuta(color) {
        var flightPath = new google.maps.Polygon({
            path: flightPlanCoordinates,
            geodesic: true,
            strokeColor: color,
            strokeOpacity: 1.0,//opacidad de contorno
            fillColor: color,
            fillOpacity: 1,//Opacidad de relleno
            strokeWeight: 4
        });
        flightPath.setMap(map2);
    }

    function addMarket(latitud, longitud, title) {
        var myLatLng = {lat:parseFloat(latitud), lng: parseFloat(longitud)};
        var marker = new google.maps.Marker({
            position: myLatLng,
            draggable:true,
            label: {
                color: '#fffdf4',
                fontWeight: '900',
                text: title
            },
            map: map2,
            title: title
        });
    }

    function setMapOnAll(map) {

        for (key in markers) {

            var marker = markers[key];
            marker.setMap(map2);
        }
        markers=[];
    }

    //var lgo, lgd, lto, ltd;
    function initMap() {
        var myLatLng = {lat: -7.1909270000000003, lng: -78.372962000000001};
        var myOptions = {
            zoom: 14,
            center: myLatLng,
            mapTypeId: 'satellite'
        };
        map = new google.maps.Map(document.getElementById('map'), myOptions);
        map2 = new google.maps.Map(document.getElementById("map_canvas2"), myOptions);
        mapAddRuta = new google.maps.Map(document.getElementById("map_canvas_addRuta"), myOptions);
    }
    function makePostInterno(data){

        $.ajax({
            async: true,
            type: "POST",
            dataType: "json",
            data: data,
            url:  $("#baseUrl").val()+"/lugar/index",
            success: function (data2) {
                if(data2.data!==-1)
                {
                   switch (data.o)
                   {
                       case 1:
                           swal(
                               {
                                   title: "Agregado!!",
                                   text: "La operación del registro fue correctamente",
                                   type: "success",
                                   confirmButtonColor: "#DD6B55",
                                   closeOnConfirm: false
                               },
                               function () {
                                   location.reload(true);
                               }
                           );
                           break;
                       case 2:
                           agregarArrayRutas(data2.data)
                           break;
                       case 3:
                           location.reload(true);
                           break;
                       case 4:
                           var html="";
                           $.each(data2.data, function (k,v) {

                               html+="<tr><td>"+v.latitud+"</td>" +
                                   "<td>"+v.longitud+"</td>" +
                                   "<td>" +
                                   "<a href='#' class='btn btn-xs btn-info estado'>Mapa</a>" +
                                   "</td></tr>";
                           });
                           tableBodyAdd.innerHTML = html;
                           break;
                   }
                }
                else {
                    swal("error","Algo fue mal, intentar nuevamente en unos segundos","error")
                }
            }

        });
    }

</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDPt2sc_jYBhNXu48FikO9-bc0eNfbB2-A&libraries=places&sensor=false&callback=initMap">
</script>

</body>