<!--
* Created by Henry Bravo cel 973772738.
-->
<?php
$this->inlineScript()->appendFile(
    $this->basePath() . '/public/js/reserva/list.js'
)
?>


<body>

<div class="row center-align">
    <div class="col-sm-12 col-md-12">
        <div class="row">

            <table width="100%" id="table-reservas" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
                <thead>
                <tr role="row">
                    <td>Nº</td>
                    <td>Cod.</td>
                    <td>Cliente</td>
                    <td>Telefono</td>
                    <td>Origen</td>
                    <td>Destino</td>
                    <td>Precio</td>
                    <td>Movilidad</td>
                    <td>Estado</td>
                    <td>Opción</td>
                </tr>
                </thead>
                <tbody>
                <?php
                    $i=0;
                    foreach ($rutas as $value)
                    {
                        $i++;
                        $precio=$value->precio;
                        if($value->precio==-1)
                        {
                            $precio="No registrado";
                        }
                        switch ($value->estado)
                        {
                            case 1:
                                $estado="Sin atender";
                                echo "
                                <tr>
                                    <td>".$i."</td>
                                    <td>".$value->idruta."</td>
                                    <td>".$value->idcliente."</td>
                                    <td>".$telefonos[$value->idruta]."</td>
                                    <td>".$value->telefono."</td>
                                    <td>".$value->origen."</td>
                                    <td>".$value->destino."</td>
                                    <td>".$precio."</td>
                                    <td>-No asignado</td>
                                    <td>".$estado."</td>
                                    <td>
                                    
                                    <a href='#' class='btn cambiar btn-xs btn-info'
                                     
                                            idr='".$value->idruta."' 
                                            lto='".$value->latitudo."'
                                            ltd='".$value->latitudd."'
                                            lgo='".$value->longitudo."'
                                            lgd='".$value->longitudd."'     
                                            op='1'
                                            >Cambiar</a>
                                
                                            
                                            </td>
                                </tr>
                                ";
                                break;
                            case 2:
                                $estado="En camino";
                                echo "
                                <tr>
                                    <td>".$i."</td>
                                    <td>".$value->idruta."</td>
                                    <td>".$value->idcliente."</td>
                                                                        <td>".$telefonos[$value->idruta]."</td>

                                    <td>".$value->origen."</td>
                                    <td>".$value->destino."</td>
                                    <td>".$precio."</td>
                                    <td>".$value->idmovilidad."</td>
                                    <td>".$estado."</td>
                                    <td>
                                     <a href='#' class='btn cambiar btn-xs btn-info'
                                     
                                            idr='".$value->idruta."' 
                                            lto='".$value->latitudo."'
                                            ltd='".$value->latitudd."'
                                            lgo='".$value->longitudo."'
                                            lgd='".$value->longitudd."'    
                                            op='2'
                                            >Cambiar</a>
                                    
                                            
                                     </td>
                                </tr>
                                ";
                                break;
                            case 5;
                                $estado="Cancelada";
                                echo "
                                <tr>
                                    <td>".$i."</td>                                   
                                     <td>".$value->idruta."</td>
                                    <td>".$value->idcliente."</td>
                                                                        <td>".$telefonos[$value->idruta]."</td>

                                    <td>".$value->origen."</td>
                                    <td>".$value->destino."</td>
                                    <td>".$precio."</td>
                                    <td>-----</td>
                                    <td>Cancelada</td>
                                    <td></td>
                                </tr>
                                ";
                                break;
                        }


                    }

                ?>

                </tbody>
            </table>
        </div>
    </div>
</div>

<div id="modal1" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Ruta</h4>
            </div>
            <div class=" row modal-body">
                <div class="row col-md-12" >
                    <div class="col-md-3" id="pre">
                        <label for="icon_telephone" class="form-label">Precio</label>
                        <input id="icon_telephone" class="validate form-control" type="tel" >
                    </div>
                    <div class="col-md-4" id="movi">
                        <label for="movilidad" class="form-label">Movilidad</label>
                        <select id="movilidad" class="form-control col-md-4">
                            <option value="0">Seleccione...</option>
                            <?php
                            foreach ($movilidad as $value)
                            {
                                echo"<option value='".$value->idmovilidad."'>".$value->nplaca."</option>";

                            }
                            ?>
                        </select>
                    </div>

                    <div class="input-field col-md-12" >
                        <label for="activo" class="form-label col-md-12">Estado</label>
                        <div class="row col-md-12">
                            <input type="radio" id="activo" name="estado" value="1"  />
                            <label for="activo">Asignar</label>
                            <input type="radio" id="activo" name="estado" value="3"  />
                            <label for="activo">Finalizado</label>
                            <input type="radio" id="cancelado"  name="estado" value="5"/>
                            <label for="cancelado">Cancelado</label>
                        </div>
                    </div>


                </div>
            </div>

            <div class="modal-footer">
                <a id="btn-s" class="btn btn-info" href="#!" idr="">Guardar</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript">

    $(document).on('click','.cambiar', function() {
        $('#modal1').modal('show');
        var idruta=$(this).attr('idr');
        $("#btn-s").attr('idr', idruta);
        $("#icon_telephone").val("");
        if($(this).attr('op')=='2')
        {
            $("#pre").hide();

            $("#movi").hide();
            $("#activo").prop('disabled', true);
        }else {
            $("#pre").show();
            $("#activo").prop('disabled', false);
            $("#movi").show();

        }
    });
    $(document).on('click','#btn-s', function() {
        $(this).empty().append('            <i class="fa fa-cog fa-spin fa-3x fa-fw"></i>            <span class="sr-only">Loading...</span>')
        var precio=$("#icon_telephone").val();
        var movilidad=$("#movilidad").val();
        var idruta=$(this).attr('idr');
        var estado=$("input[name=estado]:checked").val();
        if(precio&&movilidad||estado=='5')
        {
            makePost(
                {
                    o:1,
                    idr:idruta,
                    idm:movilidad,
                    p:precio,
                    e:estado
                })
        }else
            alert("ingrese precio y movilidad")
    });

    function makePost(data)
    {
        $.ajax({
            async: true,
            type: "POST",
            dataType: "json",
            data: data,
            url: base+"/reserva/index",
            success: function (data) {
                if(data.data!=-1)
                {
                    alert("Actualizado correctamente")

                    location.reload();
                }
                else {
                    alert("Algo fue mal, intentar nuevamente en unos segundos")

                }
            }

        });
    }


</script>

</body>