<!--
* Created by Henry Bravo cel 973772738.
-->
<?php
$this->inlineScript()->appendFile(
    $this->basePath() . '/public/js/unidad/unidad.js'
)
?>
<body>

<div class="panel-heading">
    <h3>LISTA DE UNIDADES</h3>
    <a class="btn btn-info btn-xs" id="addChofer"><i class="fa fa-plus" aria-hidden="true"></i>Chofer</a>
    <a class="btn btn-success btn-xs" id="addUnidad"><i class="fa fa-plus" aria-hidden="true"></i>Unidad</a>
</div>
<br>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                LISTA DE UNIDADES
            </div>
            <div class="table-responsive">
                <table  id="table-unidades" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline tableeeeee" role="grid" aria-describedby="dataTables-example_info" style="width: 98%;">
                    <thead>
                    <tr role="row">
                        <td>Nº Placa</td>
                        <td>Tipo</td>
                        <td>Estado</td>
                        <td>opción</td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($this->volquetes as $value)
                    {
                        $estado="";
                        switch ($value['estado'])
                        {
                            case 1:
                                $estado="Unidad en Solicitud";
                                break;
                            case 2:
                                $estado="Unidad en Servicio";
                                break;
                            case 3:
                                $estado="Unidad sin Servicio";
                                break;
                        }
                        echo "
                                <tr>
                                    <td>".$value['placa']."</td>
                                    <td>Volquete</td>
                                    <td>".$estado."</td>
                                    <td>
                                        <a href='#' class='btn btn-xs btn-info estado' idc='".$value['idunidad']."'>Estado</a>
                                    </td>
                                </tr>
                                ";


                    }
                    foreach ($this->palas as $value)
                    {
                        $estado="";
                        switch ($value['estado'])
                        {
                            case 1:
                                $estado="Unidad en Solicitud";
                                break;
                            case 2:
                                $estado="Unidad en Servicio";
                                break;
                            case 3:
                                $estado="Unidad sin Servicio";
                                break;
                        }
                        echo "
                                <tr>
                                    <td>".$value['placa']."</td>
                                    <td>Pala</td>
                                    <td>".$estado."</td>
                                    <td>
                                        <a href='#' class='btn btn-xs btn-info estado' idc='".$value['idunidad']."'>Estado</a>
                                    </td>
                                </tr>
                                ";


                    }

                    ?>


                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<div id="modalAddUnidad" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Nueva Unidad</h4>
            </div>
            <div class=" row modal-body">
               <div class="card-panel col-md-12">
                   <div class="form-group col-md-12">
                       <label class="form_label col-md-2">Tipo: </label>

                       <div class="">
                           <div class="" >
                               <div class=" col-md-1">
                                   <input class=""  type="radio" id="checkpala" name="tipounidad" value="1"  checked/>
                               </div>
                               <label for="checkpala" class="col-md-2">Pala</label>
                               <div class="col-md-1">
                                   <input class=""  type="radio" id="checkvol" name="tipounidad" value="2"  />
                               </div>
                               <label for="checkvol" class="col-md-2">Volquete</label>
                           </div>
                       </div>
                   </div>
                   <div class="form-group  col-md-12">
                       <label class="col-md-2">Nº placa: </label>
                       <div class="col-md-10">
                           <input class="form-control col-md-12" id="nplaca" placeholder="No se debe repetir">
                       </div>
                   </div>


                   <div class="col-md-12">
                       <label class="col-md-2">Consumo: </label>
                       <div class="col-md-10">
                           <input class="form-control col-md-12" id="consumo" placeholder="En galones por hora">
                       </div>
                   </div>
               </div>
            </div>

            <div class="modal-footer">
                <a id="btnGuardarU" class="btn btn-info" href="#!" idu="">Guardar</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>

    </div>
</div>
<div id="modalEditUnidad" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Editar datos de Unidad</h4>
            </div>
            <div class=" row modal-body">
               <div class="card-panel">
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Nº placa</label>
                       <input class="form-control" id="nplacaE">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Nº Interno</label>
                       <input class="form-control" id="internoE">
                   </div>
               </div>
            </div>

            <div class="modal-footer">
                <a id="btnEditUnidad" class="btn btn-info" href="#!" idr="">Actualizar</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>

    </div>
</div>
<div id="modalAsignar" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Asginar nuevo Chofer</h4>
            </div>
            <div class=" row modal-body">
               <div class="card-panel">
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Chofer</label>
                       <select id="nuevochofer" class="form-control">
                           <?php
                                foreach ($choferes as $v)
                                {
                                    echo '<option value="'.$v->idchofer.'">'.$v->nombre.'</option>';
                                }
                           ?>
                       </select>
                   </div>
               </div>
            </div>

            <div class="modal-footer">
                <a id="btnAsginar" class="btn btn-info" href="#!" idm="">Siguiente</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<div id="modalAddChofer" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Nuevo Chofer</h4>
            </div>
            <div class=" row modal-body">
               <div class="card-panel">
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Nombre Y apellidos</label>
                       <input class="form-control" id="nombre">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Dni</label>
                       <input class="form-control" id="dni">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Dirección</label>
                       <input class="form-control" id="direccion">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Telefono</label>
                       <input class="form-control" type="number" id="telefono">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Contraseña</label>
                       <input class="form-control" type="password" id="password">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Repida Contraseña</label>
                       <input class="form-control" type="password" id="passwordr">
                   </div>
               </div>
            </div>

            <div class="modal-footer">
                <a id="btnGuardarCh" class="btn btn-info" href="#!" idr="">Guardar</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<div id="modalEditChofer" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Editar Chofer</h4>
            </div>
            <div class=" row modal-body">
               <div class="card-panel">
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Nombre Y apellidos</label>
                       <input class="form-control" id="nombreE">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Dni</label>
                       <input class="form-control" id="dniE">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Dirección</label>
                       <input class="form-control" id="direccionE">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Telefono</label>
                       <input class="form-control" type="number" id="telefonoE">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Nueva Contraseña</label>
                       <input class="form-control" type="password" id="passwordE">
                   </div>
                   <div class="form-group" style="margin: 10px">
                       <label class="form_label">Repida Contraseña</label>
                       <input class="form-control" type="password" id="passwordrE">
                   </div>
               </div>
            </div>

            <div class="modal-footer">
                <a id="btnEditarCh" class="btn btn-info" href="#!" idc="">Guardar</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<div id="changeEstado" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Unidad</h4>
            </div>
            <div class=" row modal-body">
                <div class="row col-md-12" >
                    <div class="input-field col-md-5" >
                        <label for="activo" class="form-label col-md-12">Estado</label>
                        <input type="radio" id="activo" name="estado" value="1"  checked/>
                        <label for="activo">Activar</label>
                        <input type="radio" id="activo" name="estado" value="2"  />
                        <label for="activo">Desactivar</label>
                    </div>


                </div>
            </div>

            <div class="modal-footer">
                <a id="btn-confirmar" class="btn btn-info" href="#!" idc="">Confirmar</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<div id="modalLoading" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content col-md-6 col-md-offset-3">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Espere un momento</h4>
            </div>
            <div class=" row modal-body">
                <div class="col-md-12">
                    <div class="col-md-4 col-md-offset-4">
                        <i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

</body>