<?php
$this->inlineScript()->appendFile(
    $this->basePath() . '/public/js/application/index/index.js'
)
?>
<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <a href="#">
            <div class="card red summary-inline">
                <div class="card-body">
                    <i class="icon fa fa-inbox fa-4x"></i>
                    <div class="content">
                        <div class="title"><?=$ventas ?></div>
                        <div class="sub-title">Ventas en le día</div>
                    </div>
                    <div class="clear-both"></div>
                </div>
            </div>
        </a>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <a href="#">
            <div class="card yellow summary-inline">
                <div class="card-body">
                    <i class="icon fa fa-comments fa-4x"></i>
                    <div class="content">
                        <div class="title"><?=$pedidos ?></div>
                        <div class="sub-title">Pedidos del día</div>
                    </div>
                    <div class="clear-both"></div>
                </div>
            </div>
        </a>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <a href="#">
            <div class="card green summary-inline">
                <div class="card-body">
                    <i class="icon fa fa-tags fa-4x"></i>
                    <div class="content">
                        <div class="title"><?=$compras ?></div>
                        <div class="sub-title">Solicitudes de compra en el día</div>
                    </div>
                    <div class="clear-both"></div>
                </div>
            </div>
        </a>
    </div>
</div>
<div class="row  no-margin-bottom">
    <div class="col-sm-6 col-xs-12">
        <div class="row">
            <div class="col-xs-12">
                <div class="card primary">
                    <div class="card-jumbotron no-padding">
                        <canvas id="jumbotron-line-chart" class="chart no-padding"></canvas>
                    </div>
                    <div class="card-body half-padding">
                        <h4 class="float-left no-margin font-weight-300">Ingresos</h4>
                        <h2 class="float-right no-margin font-weight-300">S/.<?=$soles ?>&nbsp;&nbsp;$ <?=$dolares ?></h2>
                        <div class="clear-both"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-xs-12">
        <div class="row">
            <div class="col-xs-12">
                <div class="card primary">
                    <div class="card-jumbotron no-padding">
                        <canvas id="jumbotron-line-chart" class="chart no-padding"></canvas>
                    </div>
                    <div class="card-body half-padding">
                        <h4 class="float-left no-margin font-weight-300">Egresos</h4>
                        <h2 class="float-right no-margin font-weight-300">S/. <?=$egresos ?></h2>
                        <div class="clear-both"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>