<?php
$this->inlineScript()->appendFile(
    $this->basePath() . '/public/js/application/index/responsables.js'
)
?>
<style>
    tbody {
        display: table-row-group;
        vertical-align: middle;
        border-color: inherit;
    }
</style>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Módulo de Responsables del sistema</h1>
        <a id="nS" class="btn btn-success" data-toggle="modal" href="#modalNR">
            <i class="fa fa-plus"></i> Nuevo Responsable
        </a>
    </div>

</div>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary" >
            <div class="panel-heading" >
                LISTA DE RESPONSABLES
            </div>
            <div class="panel-body">
                <div class="dataTable_wrapper">

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="table-responsive">
                                <table width="100%" id="table-responsables" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
                                    <thead>
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="table-users" rowspan="1" colspan="1" style="width: 306px;" aria-label="Platform(s): activate to sort column ascending">Nombres</th>
                                        <th class="sorting" tabindex="0" aria-controls="table-users" rowspan="1" colspan="1" style="width: 306px;" aria-label="Platform(s): activate to sort column ascending">Descripcion</th>
                                        <th class="sorting" tabindex="0" aria-controls="table-users" rowspan="1" colspan="1" style="width: 306px;" aria-label="Platform(s): activate to sort column ascending">Oficina</th>
                                        <th class="sorting" tabindex="0" aria-controls="table-users" rowspan="1" colspan="1" style="width: 306px;" aria-label="Platform(s): activate to sort column ascending">Tipo</th>
                                        <th class="sorting" tabindex="0" aria-controls="table-users" rowspan="1" colspan="1" style="width: 306px;" aria-label="Platform(s): activate to sort column ascending">Estado</th>
                                        <th class="sorting" tabindex="0" aria-controls="table-users" rowspan="1" colspan="1" style="width: 306px;" aria-label="Platform(s): activate to sort column ascending">Opción</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    <?php
                                    $i=0;
                                    foreach ($responsables as $key => $value) {
                                        $estado="No estado";
                                        switch($value->estado)
                                        {
                                            case 1:
                                                $estado="Activo";
                                                break;
                                            case 2:
                                                $estado="No activo";
                                                break;
                                        }
                                        $tipo="No tipo";
                                        switch($value->tipo)
                                        {
                                            case 1:
                                                $tipo="Compras";
                                                break;
                                            case 2:
                                                $tipo="Ventas";
                                                break;
                                            case 3:
                                                $tipo="Pedidos";
                                                break;
                                            case 4:
                                                $tipo="Almacen";
                                                break;
                                            case 5:
                                                $tipo="Cotización";
                                                break;
                                            case 6:
                                                $tipo="Caja";
                                                break;
                                            case 7:
                                                $tipo="Rrhh";
                                                break;
                                        }
                                            echo '<tr >' .
                                                '<td class="" > ' . $this->escapeHtml($empleaditos[$value->idempleado]) . '</td> ' .
                                                '<td class=""> ' . $this->escapeHtml($value->descripcion) . '</td> ' .
                                                '<td class=""> ' . $this->escapeHtml($oficis[$value->idoficina]) . '</td> ' .
                                                '<td class=""> ' . $this->escapeHtml($tipo) . '</td> ' .
                                                '<td class=""> ' . $this->escapeHtml($estado) . '</td> '.
                                                '<td class=""><div class="btn-group dropup btn-xs">
                                                              <button type="button" class="btn btn-warning dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                <span class="caret"></span>
                                                                <span class="sr-only">Toggle Dropdown</span>
                                                              </button>
                                                              <ul class="dropdown-menu">
                                                                <li><a href="#" class="changeEs" val="1" ide="'.$value->idempleado.'" ido="'.$value->idoficina.'" t="'.$value->tipo.'">Activar</a></li>
                                                                <li><a href="#" class="changeEs" val="2" ide="'.$value->idempleado.'" ido="'.$value->idoficina.'" t="'.$value->tipo.'">Remover</a></li>
                                                              </ul>
                                                            </div></td> ';


                                    }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalNR"  role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" id="myModalLabel">Nuevo Responsable</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        <label>Empleado:</label>
                        <select class="col-md-12" id="idE">
                            <option value="">Seleccione empleado</option>
                            <?php
                            foreach($this->empleados as $value)
                            {
                                echo "<option value='".$value->idempleado."'>".$value->nombre." ".$value->apellidop."</option>";
                            }
                            ?>
                        </select>
                    </div>
                    <div class="form-group col-md-12">
                        <label>Oficina:</label>
                        <select class="col-md-12" id="idO">
                            <option value="">Seleccione oficina</option>
                            <?php
                            foreach($this->oficinas as $value)
                            {
                                echo "<option value='".$value->idoficina."'>".$value->direccion."</option>";
                            }
                            ?>
                        </select>
                    </div>
                    <div class="form-group col-md-12">
                        <input type="checkbox" name="estado" id="compra" value="1"/>
                        <label for="compra">Compras</label>

                        <input type="checkbox" name="estado" id="venta" value="2"/>
                        <label for="venta">Ventas</label>

                        <input type="checkbox" name="estado" id="pedido" value="3"/>
                        <label for="pedido">Pedidos</label>

                        <input type="checkbox" name="estado" id="almacen" value="4"/>
                        <label for="almacen">Almacen</label>

                        <input type="checkbox" name="estado" id="coti" value="5"/>
                        <label for="coti">Cotización</label>

                        <input type="checkbox" name="estado" id="caja" value="6"/>
                        <label for="caja">Caja</label>

                        <input type="checkbox" name="estado" id="rrhh" value="7"/>
                        <label for="rrhh">RRHH</label>
                    </div>

                    <div class="form-group col-md-12">
                        <label>Descripción:</label>
                        <textarea class="form-control col-md-12" id="Des"></textarea>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="btnGNS">Guardar</button>
            </div>
        </div>
    </div>
</div>